# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://github.com/sayyid5416/pyinstaller/blob/main/README.md

name: treemd

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1.3.0
        with:
          python_ver: '3.12'
          spec: 'treemd.py'
          upload_exe_with_name: 'treemd' 
          options: --onefile, --name "treemd", --noconsole, 
